config/routes.rb
Rails.application.routes.draw do
  
  resources :messages
  
  get "/messages/new/:user_id" => 'messages#new'
  get "/indexre" => 'messages#indexre'
  devise_for :users
  root 'post#index'
  
  get '/user' => 'post#user'
  get '/index' => 'post#index'
  get '/new' => 'post#new'
  resources :posts, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  post '/create' => 'post#create'
  get '/mypage/:user_id' => 'post#mypage'
  get '/destroy/:postid' => 'post#destroy'
  
  get '/edit/:postid' => 'post#edit'
  
  post '/update/:postid' => 'post#update'
  
  get '/show/:postid' => 'post#show'
  get '/questions' => 'post#questions'
  
  get '/soccer' => 'post#soccer'
  get '/basketball' => 'post#basketball'
  get '/baseball' => 'post#baseball'

  post '/show/:postid/comments/create' => 'comments#create'
  post '/show/:postid/comments/destroy/:comment_id' => 'comments#destroy'
  
  #freepost
  get '/free/index' => 'freepost#index'
  post '/free/create' => 'freepost#create'
  get '/free/new' => 'freepost#new'
  get '/free/show/:postid' => 'freepost#show'
  get '/free/destroy/:postid' => 'freepost#destroy'
  get '/free/edit/:postid' => 'freepost#edit'
  post '/free/update/:postid' => 'freepost#update'
  post "/like/likes_toggle" => "likes#like_toggle"

  resources :freeposts, except: [:show] do
    resources :free_comments, only: [:create, :destroy]
    post "/like", to: "likes#like_toggle"
  end
end

app/models/freepost.rb
class Freepost < ApplicationRecord
       belongs_to :user
       has_many :free_comments
       has_many :impressions, :as=>:impressionable
       def impression_count
           impressions.size
       end
       has_many :likes
       has_many :liked_users, through: :likes, source: :user        
       def unique_impression_count
           # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
           # so getting keys from the hash and calculating the number of keys
           impressions.group(:ip_address).size.keys.length #TESTED
       end
end

app/controllers/freepost_controller.rb
class FreepostController < ApplicationController
    before_action :authenticate_user!
    before_action :log_impression, :only=> [:show]

    def log_impression
        @hit_post = Freepost.find(params[:postid])
        # this assumes you have a current_user method in your authentication system
        @hit_post.impressions.create(ip_address: request.remote_ip,user_id:current_user.id)
    end
    
    def index
      @posts = Freepost.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    end
    
    def create
        @post = Freepost.new(user_id: current_user.id, content: params[:content]) # DB테이블의 새로운 한 행을 생성한다.
        @post.title = params[:post_title]
        @post.content = params[:post_content]
        @post.save
        
        redirect_to '/free/index'
    end
    
    def new
    end
    
    def show
        @show = Freepost.find(params[:postid])
    end
    
    def destroy
        @destroypost = Freepost.find(params[:postid])
        @destroypost.destroy
        
        redirect_to '/free/index'
    end
    
    def edit
        @editpost = Freepost.find(params[:postid])
    end
    
    def update
        @updatepost = Freepost.find(params[:postid])
        @updatepost.title = params[:post_title]
        @updatepost.content = params[:post_content]
        @updatepost.save
        
        redirect_to "/free/index"
    end
end

app/helpers/freepost_helper.rb
module FreepostHelper
end

app/views/freepost/edit.html.erb
<html>
  <head>
    <style>
      label{
        font-size:15px;
      }
      body{
        font-family:arial;
      }
    </style>
  </head>
  <body>
    <br>
     <div class="container">
          <form action="/free/update/<%= @editpost.id %>" method="post">
             <div class="form-group">
                <label for="exampleInputEmail1">제목</label>
                <input type="text" class="form-control" name="post_title" value="<%= @editpost.title %>">
              </div>
            
            
              <div class="form-group">
                <%= tinymce %>
                <label for="exampleInputcontent">내용</label>
                <textarea class="form-control tinymce" name="post_content" rows="20"><%= @editpost.content %></textarea>
              </div>
              <div style="float:right">
              <button type="submit" class="button">쓰기</button>
              <a href="/free/index"><button class="button">취소</button></a>
              </div>
          </form>
        </div>
<!--<br>-->
<!-- <div class="container">-->
<!--      <%= form_tag '/create', method: 'post' do %>-->
<!--         <div class="form-group">-->
<!--            <label for="exampleInputEmail1">제목</label>-->
<!--            <%= text_field_tag 'post_title', nil, class: "form-control", placeholder:"제목을 입력해주세요." %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
        
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">운동 종목</label>-->
<!--            <%= text_field_tag 'post_sports', nil, class: "form-control", placeholder: "운동 종목을 입력해주세요." %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">지역</label>-->
<!--            <%= text_field_tag 'post_region', nil, class: "form-control", placeholder: "예) OO도 OO시 OO동" %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">날짜</label>-->
<!--            <%= text_field_tag 'post_date', nil, class: "form-control", placeholder: "예) OOOO년-OO월-OO일" %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">시간</label>-->
<!--            <%= text_field_tag 'post_time', nil, class: "form-control", placeholder: "예) OO시-OO시" %> -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <%= tinymce %>-->
<!--            <label for="exampleInputcontent">추가 내용</label>-->
<!--            <%= text_area_tag 'post_content', nil, class: "form-control tinymce", rows:30, placeholder: "추가할 정보를 입력해주세요. 예)핸드폰 번호, 경기장 이름 등" %> -->
<!--             내용을 작성한 뒤 '저장하는 기능'으로 넘길 때, 작성한 내용을 post_content에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <%= submit_tag '쓰기', class: "btn btn-default" %>-->
<!--          <a href="/index" class="btn btn-default">취소</a>-->
<!--      <% end %>-->
<!--  </div>-->
  </body>
</html>

app/views/freepost/index.html.erb
<html>
  <head>
    <style>

    </style>
  </head>
  <body>
  <div class="container">
  <div>
      <center>
        <h2>자유 게시판</h2>
        <div style="padding-bottom:20px; width:100%">
           <input type="text" class="form-control" placeholder="Search" style="width:70%; display:inline;">
           <button type="submit" class="button">검색</button>
        </div>
      </center>
    <!-- new.html.erb에 새 글 쓰는 양식을 생성 -->
    <table class="table" style="background-color:#ffffff; border:1px solid #e8e5e5; text-align:center;">
      <thead>
      <tr>
        <th style="width:60%; background-color:#EAEAEA"><center><a style="float:left; text-decoration: none;">제목</a></center></th>
        <th style="width:10%; background-color:#EAEAEA"><center>작성자</center></th>
        <th style="width:10%; background-color:#EAEAEA"><center>작성일</center></th>
        <th style="width:10%; background-color:#EAEAEA"><center>조회 수</center></th>
        <th style="width:10%; background-color:#EAEAEA;"><center>좋아요</center></th>
      </tr>
      </thead>
      <tbody>
      <% @posts.each do |post| %>
        <!-- @posts=Post.all이다. 전체 테이블의 각 줄을 post로 지정 -->
        <!-- do와 end사이의 코드는 테이블 첫째 줄부터 마지막 줄까지 반복 -->
        <tr>
          <td style="font-family:italic; font-size:15px"><center><a href="/free/show/<%= post.id %>" style="float:left"><%= post.title %></a></center></td>
          <td><center><%= post.user.name %></center></td>
          <td><center><%="#{time_ago_in_words(post.created_at)} 전"%></center></td>
          <td><center><%= "#{post.unique_impression_count}" %></center></td>
          <% if current_user.is_like?(post) %>
          <td><center><a data-method="post" href="/freeposts/<%= post.id %>/like">좋아요 취소</a></center></td>
          <% else %>
          <td><center><a data-method="post" href="/freeposts/<%= post.id %>/like">좋아요</a></center></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    
    <div style="float:right; margin-bottom:20px;">   
      <a href="/free/new"><button class="button">글쓰기</button></a>
    </div>
    <br><br>
    <div style="float:center; padding-left:60px;">
      <center><%= will_paginate @posts, :previous_label => '이전', :next_label => '다음' %></center>
    
    </div>
    </div>

</body>

</html>

app/views/freepost/new.html.erb
<html>
  <head>
    <style>
      label{
        font-size:15px;
      }
      body{
        font-family:arial;
      }
    </style>
  </head>
  <body>
    <br>
     <div class="container">
          <form action="/free/create" method="post">
             <div class="form-group">
                <label for="exampleInputEmail1">제목</label>
                <input type="text" class="form-control" name="post_title" placeholder="제목을 입력해주세요.">
              </div>
            
            
              <div class="form-group">
                <%= tinymce %>
                <label for="exampleInputcontent">내용</label>
                <textarea class="form-control tinymce" name="post_content" rows="20" placeholder="추가할 정보를 입력해주세요. 예)핸드폰 번호, 경기장 이름 등"></textarea>
              </div>
              <div style="float:right">
              <button type="submit" class="button">쓰기</button>
              <a href="/free/index"><button class="button">취소</button></a>
              </div>
          </form>
        </div>
<!--<br>-->
<!-- <div class="container">-->
<!--      <%= form_tag '/create', method: 'post' do %>-->
<!--         <div class="form-group">-->
<!--            <label for="exampleInputEmail1">제목</label>-->
<!--            <%= text_field_tag 'post_title', nil, class: "form-control", placeholder:"제목을 입력해주세요." %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
        
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">운동 종목</label>-->
<!--            <%= text_field_tag 'post_sports', nil, class: "form-control", placeholder: "운동 종목을 입력해주세요." %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">지역</label>-->
<!--            <%= text_field_tag 'post_region', nil, class: "form-control", placeholder: "예) OO도 OO시 OO동" %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">날짜</label>-->
<!--            <%= text_field_tag 'post_date', nil, class: "form-control", placeholder: "예) OOOO년-OO월-OO일" %> <!-- 2번째는 value -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <label for="exampleInputEmail1">시간</label>-->
<!--            <%= text_field_tag 'post_time', nil, class: "form-control", placeholder: "예) OO시-OO시" %> -->
<!--             제목 작성 후 '저장하는 기능'으로 넘길 때, 작성한 제목을 post_title에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <div class="form-group">-->
<!--            <%= tinymce %>-->
<!--            <label for="exampleInputcontent">추가 내용</label>-->
<!--            <%= text_area_tag 'post_content', nil, class: "form-control tinymce", rows:30, placeholder: "추가할 정보를 입력해주세요. 예)핸드폰 번호, 경기장 이름 등" %> -->
<!--             내용을 작성한 뒤 '저장하는 기능'으로 넘길 때, 작성한 내용을 post_content에 저장해서 넘긴다. -->
<!--          </div>-->
          
<!--          <%= submit_tag '쓰기', class: "btn btn-default" %>-->
<!--          <a href="/index" class="btn btn-default">취소</a>-->
<!--      <% end %>-->
<!--  </div>-->
  </body>
</html>

app/views/freepost/show.html.erb
<html>
  <head>
    <style>
      a:link{color:grey;}
      
    </style>
  </head>
<div class=container>
<h1>자유 게시판</h1><hr>
  <div class="container" style="border:1px solid #e8e5e5; background-color:white;">
  
    <p style="">
    <div class="container">
      <div>    
        <h2 style="margin-top:0px;"><%= @show.title %></h2>
        <h5 style="color:grey; padding-right:20px" align="right"><%= @show.user.name %>&nbsp;&nbsp;&nbsp;<%= "#{time_ago_in_words(@show.created_at)} 전" %>&nbsp;&nbsp;&nbsp; <%= "#{@show.unique_impression_count}명 읽음" %>&nbsp;&nbsp;&nbsp;            
        <%= @show.likes.size %> 명이 좋아합니다.
        </h5>
        <hr style="margin-right:20px">
      </div>
    <h6>
      <strong style="font-size:15px" >
      <div><%= @show.content.html_safe %></div>
      </strong><br>
    </h6>
   </p>

    <br>
  </div>
  </div>
<br>
<span style="float:right">
<a href="/free/index"><button class="button">글 목록</button></a>
<% if current_user.id == @show.user_id %> <!-- 자신의 글이면 수정,삭제 기능 추가 -->
  <a href="/free/edit/<%= @show.id %>"><button type="button" class="button">수정</button></a> <!-- Routes의 /edit/:postid 액션으로 전달 -->
  <a href="/free/destroy/<%= @show.id %>" data-confirm="정말 삭제하시겠습니까?"><button type="button" class="button">삭제</button></a> <!-- Routes의 /destroy/:postid 액션으로 전달 -->
<% end %>
</span><br><br>
<hr>

 <div class="container" style="border:1px solid #e8e5e5; background-color:white;">
  
    <div style="padding-left:10px"><h2>댓글 목록</h2><hr style="margin-top:10px; margin-bottom:10px">
        <% @show.free_comments.each do |c| %>
          <strong style="display:inline; font-size:17px"><%= c.user.name %></strong> &nbsp;&nbsp;
          <h5 style="display:inline; color:grey"><%= "#{time_ago_in_words(c.created_at)} 전" %>&nbsp;&nbsp;          
          <% if current_user.id == c.user.id %>
            <%= link_to "삭제", freepost_free_comment_path(@show, c), method: "delete" %>
          <% end %>
          </h5> 
          <h5> <%= c.content %>   </h5>
          <hr style="margin-top:10px; margin-bottom:10px">
        <% end %>
    </div>

    <br>
  </div>
  <br>
<h4><strong>댓글 쓰기</strong></h4>
<%= form_tag freepost_free_comments_path(@show) do %>
  <input type='text' class="form-control" name='input_comment' style="display:inline; "><br><br>
  <button type="submit" style="float:right; " class="button" >쓰기</button><br><br>
<% end %>

<hr>